# MongoDB Configuration
# Set MONGO_URI to empty to run without MongoDB
# Or set it to a valid connection string (e.g., mongodb://localhost:27017)
MONGO_URI="INSERT_YOUR_MONGO_URI"
MONGO_DB="INSERT_YOUR_MONGO_DB_NAME"
MONGO_PRODUCTS_COLLECTION="INSERT_YOUR_MONGO_PRODUCTS_COLLECTION_NAME"
MONGO_SCORES_COLLECTION="INSERT_YOUR_MONGO_SCORES_COLLECTION_NAME"

# LLM Configuration for Groq API
GOOGLE_API_KEY = "INSERT_YOUR_GOOGLE_API"
